### ISSUE TITLE
Ссылки на скачиваемые образы на главной странице

### ISSUE THREAD

**Issue by Alexmelman88** [OlegShchavelev/ALTRegularGnomeWiki#11]
У меня есть предложение, чтобы на главной странице были две ссылки, на current и tested сборки, с указанием даты сборки и кратким пояснением, чем они отличаются, это было бы уместно, если пользователь хочет протестировать новейшую сборку.

**Comment by vasik661** [comment]
Привет всем. Не смог скачать дистр. (у меня по каким-то причинам доступ запрещен) по приложенной ссылке. Не плохо было бы приложить в wiki и альтернативные ссылки, сделать отдельную страницу со списком ссылок.

**Comment by iDevPro** [comment]
До кучи еще бы выбор архитектуры, а то надо лезть в документ что-бы найти ссылку на aarch64 к примеру )
