### ISSUE TITLE
Добавить Markdown Containers: Alignment, Highlights

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTRegularGnomeWiki#112]
Необходимо вести несколько новых  Markdown Containers с помощью:

Alignments
https://vitepress-theme-default-plus.lando.dev/markdown/alignments.html

Highlights
https://vitepress-theme-default-plus.lando.dev/markdown/highlights.html

Пример для реализации.
https://github.com/lando/vitepress-theme-default-plus

**Comment by Ampernic** [comment]
Это тоже бы закрыть.
