### ISSUE TITLE
добавление к статье 

### ISSUE THREAD

**Issue by Anexya** [OlegShchavelev/ALTRegularGnomeWiki#14]
Нашел команду решающую проблему с раскладкой в статье https://alt-gnome.wiki/steam.html#не-работают-клавиши-управления-в-игре-при-нативном-запуске-без-proton
-input_button_code_is_scan_code прошу добавить в статью

**Comment by Armatik** [comment]
Параметр запуска рабочий, Постараюсь в ближайшее время добавить в вики. Спасибо!

**Comment by OlegShchavelev** [comment]
Проверяем.
