### ISSUE TITLE
Добавить синтаксис Vala для shiki

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTRegularGnomeWiki#278]
Добавить возможность синтаксиса Vala в shiki

Пример страницы:
https://alt-gnome.wiki/vala.html

**Comment by Ampernic** [comment]
Добавлено в PR #285

**Comment by OlegShchavelev** [comment]
@Ampernic мы закрываем?

**Comment by Ampernic** [comment]
> @Ampernic мы закрываем?

Да.
