### ISSUE TITLE
Добавить рендер: Установить из Центра приложений

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTRegularGnomeWiki#45]
Добавить метку в md, которая будет вызывать блок с кнопкой. При нажатии на кнопку в операционной системе открывается Центр Приложений, на детальной карточки приложения. Пользователю необходимо только нажать кнопку установить.

Примеры для реализации:

[snapcraft](https://snapcraft.io/telegram-desktop)
[gdm-settings](https://gdm-settings.github.io/)

Необходимо принять решение, должен ли пользователь самостоятельно выбирать источник, или источник должен определяться меткой

**Comment by pokedim13** [comment]
Понял что ты хочешь... Нужно добавить парсер, или бд, c ссылками на flathub (другие не поддерживают такого вида махинации вроде, и библиотек не нашёл для такого) вида appstream://
![Снимок экрана от 2023-11-30 02-21-56](https://github.com/OlegShchavelev/ALTRegularGnomeWiki/assets/72319244/a498d905-e06b-43e5-b8a3-a59beb6da5ac)

**Comment by OlegShchavelev** [comment]
Вопрос рендера ссылок
https://github.com/vuejs/vitepress/issues/2240

**Comment by OlegShchavelev** [comment]
Пример:
https://alt-gnome.wiki/boxes.html
