### ISSUE TITLE
Перевести кнопку в секции Участники на главной странице

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTRegularGnomeWiki#53]
Перевести Sponsors -> Поддержать
![image](https://github.com/OlegShchavelev/ALTRegularGnomeWiki/assets/20732384/ddfc72c9-bd72-410a-84a3-0d2d63da6337)

**Comment by pokedim13** [comment]
Зашито где-то глубоко в логике vitepress расширения, issue уже отправил
