### ISSUE TITLE
Структурирование страниц приложений

### ISSUE THREAD

**Issue by fiersik** [OlegShchavelev/ALTRegularGnomeWiki#72]
Из-за отсутствия общей структуры, страницы приложений сильно различаются, предлагаю внести следующие изменения:

- [x] Привести описание всех приложений в вид "[Название] — это [описание]"
----
- [x] Отсортировать источники установки в таком порядке

   - Установка из репозитория (если есть)
   - Установка c помощью Flatpak (если есть)
   - Установка c помощью Snap (если есть)
   - Установка c помощью EPM (если есть)
   - Установка из репозитория GitHub (если нет в Sysphus)
   - Установка с официального сайта (если нет на GitHub)
   - Установка из исходного кода (если собранного пакета нет)

**Comment by iDevPro** [comment]
Установка c помощью EPM (если есть) сразу после Сизифа )

**Comment by iDevPro** [comment]
Привести описание всех приложений в вид "[Название] — это [описание]" - не все можно вот так описать :)

**Comment by fiersik** [comment]
> Установка c помощью EPM (если есть) сразу после Сизифа )

epm и EPM - разные вещи

**Comment by iDevPro** [comment]
> > Установка c помощью EPM (если есть) сразу после Сизифа )
> 
> epm и EPM - разные вещи

И в чем же ?)))

**Comment by OlegShchavelev** [comment]
> @iDevPro epm -i - алиас к sudo apt-get install epm play - качает и собирает пакет непойми откуда (так скажем)

Не пойми откуда, а по ссылке, которая указанна в установочном сценарии, как правила это официальные ресурсы производителя. Но все зависит от автора установочного сценария.
