### ISSUE TITLE
Добавить боковой бар к статье.

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTRegularGnomeWiki#75]
Разработать боковой бар, по содержанию он будет напоминать блока Центра Приложений
![image](https://github.com/OlegShchavelev/ALTRegularGnomeWiki/assets/20732384/a20cf719-9a96-4f99-83a4-f22744922766)

В него входит содержание:

- Логотип приложения
- Сайт проекта
- Packages
- Помочь с переводами
- Сообщить о проблеме
- Лицензия
- Авторы приложения

Визуальный прототип 
![image](https://github.com/OlegShchavelev/ALTRegularGnomeWiki/assets/20732384/9f6c8af1-54fa-47fc-a586-2f8ab5f64c95)

**Comment by OlegShchavelev** [comment]
Необходимо добавить интерфейс по умолчанию **X11/Wayland**

**Comment by fiersik** [comment]
Необходимо добавить в бар кнопки установки приложения из источников Sisyphus и Flatpak.

**Comment by OlegShchavelev** [comment]
> Необходимо добавить в бар кнопки установки приложения из источников Sisyphus и Flatpak.

Второй версии, подумаем.

**Comment by OlegShchavelev** [comment]
@iDevPro, правильно я помню что ты хотел ввести поле: оконный интерфейс?

**Comment by iDevPro** [comment]
> @iDevPro, правильно я помню что ты хотел ввести поле: оконный интерфейс в боковой бар?

Да, так как пользователь не в курсе что у него запустится в итоге,
`X11`, `XWayland`, `Wayland` ?

Данную информацию надо по возможности добавить, что-бы потом не было проблем с тем почему у пользователя отображается окно специфично )

**Comment by OlegShchavelev** [comment]
> > @iDevPro, правильно я помню что ты хотел ввести поле: оконный интерфейс в боковой бар?
> 
> Да, так как пользователь не в курсе что у него запустится в итоге, `X11`, `XWayland`, `Wayland` ?
> 
> Данную информацию надо по возможности добавить, что-бы потом не было проблем с тем почему у пользователя отображается окно специфично )

Хочу дополнить, X11(XWayland) и Wayland, но очень часто бывает, что в зависимости от способа установки параметры запуска отличается, в том числе и оконный интерфейс.

**Comment by OlegShchavelev** [comment]
Я думаю сначала данную проблему нужно решить @iDevPro 
https://github.com/OlegShchavelev/ALTRegularGnomeWiki/issues/161
