### ISSUE TITLE
Добавить модуль Changelog & File history в VitePress

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTRegularGnomeWiki#77]
Ссылка на пакет:
https://nolebase-integrations.ayaka.io/pages/en/integrations/vitepress-plugin-git-changelog/

![image](https://github.com/OlegShchavelev/ALTRegularGnomeWiki/assets/20732384/cc8aa81e-1f2a-4eff-a125-e765685ec9b7)

**Comment by Ampernic** [comment]
#276 Добавлено в данном PR
