### ISSUE TITLE
Реализовать возможность добавлять автора/ов статьи.

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTRegularGnomeWiki#90]
Решение по добавлению авторов:
https://nolebase-integrations.ayaka.io/pages/en/integrations/vitepress-plugin-git-changelog/
![image](https://github.com/OlegShchavelev/ALTRegularGnomeWiki/assets/20732384/a9cfaa09-f0d6-46c4-905c-16efb5449036)

**Comment by Ampernic** [comment]
#276 Добавлено в данном PR
